acme_store:
    resource: "@AcmeStoreBundle/Resources/config/routing.yml"
    prefix:   /

cuse_privay_repo_cental:
    resource: "@CUSEPrivayRepoCentalBundle/Resources/config/routing.yml"
    prefix:   / #prefix:   /admin -> final path of /admin/hello/{name} instead of simply /hello/{name}

