# app/config/security.yml
# If you don't need to customize your 'login_path' or 'check_path' values 
# (the values used here are the default values), you can shorten your configuration:
# form_login: ~

security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /hello/nattaphat
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    access_control:
        - { path: ^/admin, roles: ROLE_USER_IP, ip: 127.0.0.1 }
        - { path: ^/admin, roles: ROLE_USER_HOST, host: localhost}
        - { path: ^/admin, roles: ROLE_USER_METHOD, methods: [POST, PUT] }
        - { path: ^/admin, roles: ROLE_USER }
        
        

# security:
#     encoders:
#         Symfony\Component\Security\Core\User\User: plaintext
# 
#     role_hierarchy:
#         ROLE_ADMIN:       ROLE_USER
#         ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
# 
#     providers:
#         in_memory:
#             memory:
#                 users:
#                     user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                     admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
# 
#     firewalls:
#         dev:
#             pattern:  ^/(_(profiler|wdt)|css|images|js)/
#             security: false
# 
#         login:
#             pattern:  ^/demo/secured/login$
#             security: false
# 
#         secured_area:
#             pattern:    ^/demo/secured/
#             form_login:
#                 check_path: _security_check
#                 login_path: _demo_login
#             logout:
#                 path:   _demo_logout
#                 target: _demo
#             #anonymous: ~
#             #http_basic:
#             #    realm: "Secured Demo Area"
# 
#     access_control:
#         #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
