# src/Acme/BlogBundle/Resources/config/validation.yml
Acme\BlogBundle\Entity\Author:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
            
    properties:
        gender:
            - Choice: { choices: [male, female], message: Choose a valid gender. }
            
    getters:
        passwordLegal:
            - "True": { message: "The password cannot match your first name" }
            
    properties:
        email:
            - Email: { groups: [registration] }
        password:
            - NotBlank: { groups: [registration] }
            - Length: { min: 7, groups: [registration] }
        city:
            - Length:
                min: 2