BofSystemUser:
    type: entity
    table: bof_system_user
    fields:
        userid:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        groupId:
            type: smallint
            nullable: false
            column: group_id
        depId:
            type: integer
            unsigned: false
            nullable: true
            column: dep_id
        username:
            type: string
            length: 20
            fixed: false
            nullable: false
        password:
            type: string
            length: 50
            fixed: false
            nullable: false
        pseudonym:
            type: string
            length: 50
            fixed: false
            nullable: false
        firstName:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: first_name
        lastName:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: last_name
        orgName:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: org_name
        email:
            type: string
            length: 50
            fixed: false
            nullable: false
        address:
            type: string
            length: 250
            fixed: false
            nullable: false
        workphone:
            type: string
            length: 50
            fixed: false
            nullable: false
        mobile:
            type: string
            length: 50
            fixed: false
            nullable: false
        fax:
            type: string
            length: 50
            fixed: false
            nullable: false
        postcode:
            type: string
            length: 5
            fixed: false
            nullable: false
        provinceCode:
            type: string
            length: null
            fixed: true
            nullable: false
            column: province_code
        superuser:
            type: string
            length: null
            fixed: true
            nullable: true
        jobtitle:
            type: string
            length: 50
            fixed: false
            nullable: false
        notes:
            type: text
            nullable: false
        active:
            type: string
            length: null
            fixed: true
            nullable: false
        createDate:
            type: string
            length: null
            fixed: false
            nullable: false
            column: create_date
        lastLoginIp:
            type: string
            length: 15
            fixed: false
            nullable: false
            column: last_login_ip
        lastLoginHost:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: last_login_host
        userParam:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: user_param
        prefImapIntegration:
            type: smallint
            nullable: false
            column: pref_imap_integration
        userCode:
            type: string
            length: null
            fixed: true
            nullable: true
            column: user_code
        lastLogin:
            type: datetime
            nullable: true
            column: last_login
    lifecycleCallbacks: {  }
